### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by morozovsk** [patlevin/tfjs-to-tf#22]
It would be nice to have docker file.
So it would be easier to try your library.

I use last version of ubuntu 20.04 and I tried `python setup.py` and `python3 setup.py`
but I have errors like this:
`File "setup.py", line 2
SyntaxError: Non-ASCII character '\xc2' in file setup.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`

and this:

`
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
`

So I can't easy reproduce your results. If I would have docker file like [this](https://github.com/php-opencv/php-opencv-examples/blob/master/docker/ubuntu-18.04_opencv-4.0.1/Dockerfile) I could.

**Comment by patlevin** [comment]
You can just install the package using pip if you experience problems.

**Comment by morozovsk** [comment]
Thanks. It helped a lot.

**Comment by patlevin** [comment]
@morozovsk 
Just in case you might still find it useful, here's a working (but not particularly optimised) docker file for the latest builds.
You can find it [here](https://github.com/patlevin/tfjs-to-tf/tree/master/docker).
