### ISSUE TITLE
TypeError: an integer is required (got type str) 

### ISSUE THREAD

**Issue by JaxSulav** [patlevin/tfjs-to-tf#3]
i faced, TypeError: an integer is required (got type str) in line 56 of api.py
In this line:
string = ''.join(map(chr, array))

**Comment by patlevin** [comment]
Please provide a link to the TFJS model you used, otherwise I cannot reproduce the problem.

**Comment by JaxSulav** [comment]
https://drive.google.com/open?id=1szvO4iMT-yRftfoNypoIdpQg3MEYpJKT
Here. :)

**Comment by patlevin** [comment]
Thanks for the link. I could reproduce the issue.
Expect a fix within the next couple of hours👍
