### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by alexdufetel** [patlevin/tfjs-to-tf#33]
I am running into this issue when running the converter:
zsh: illegal hardware instruction

I'm on a Macbook pro M1 and python 3.8.8

**Comment by patlevin** [comment]
Apple has their own closed-source Tensorflow fork for the M1 and the x86 version is known to cause [issues on the M1](https://stackoverflow.com/questions/65892605/illegal-hardware-instruction-import-tensorflow-macbook-m1).

You will need to install [Apple's version](https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html) instead and try that.

This is unfortunately not an issue that I can do anything about.
