### ISSUE TITLE
Location of path/to/js/model ?

### ISSUE THREAD

**Issue by khg2478** [patlevin/tfjs-to-tf#34]
Hello. It seems that this repository is what I have been looking for.

I wish to convert a blazepose model into pb file such that I can do the transfer learning from it.

However, I am not sure where I can find those js models?? Could you tell me where I can find them?

**Comment by patlevin** [comment]
You can find TensorFlowJS models on the official [TensorFlow Hub](https://tfhub.dev).

If you search for "blazepose" in the search bar of the site, you will find [a few possible matches](https://tfhub.dev/s?deployment-format=tfjs&q=blazepose).

The one that seems to be available for download is [blazeposedetector](https://tfhub.dev/mediapipe/tfjs-model/blazeposedetector/1/default/1).

HTH

**Comment by khg2478** [comment]
I see. Thanks for your prompt reply and useful source codes.
