### ISSUE TITLE
Converting.... Error: 226 nodes in a cycle

### ISSUE THREAD

**Issue by zighem25** [patlevin/tfjs-to-tf#39]
**System information**

OS Platform and Distribution: Ubuntu 18.04.5 LTS
TensorFlow version: 2.9.1
Keras version:  2.9.0

I'm getting _Converting.... Error: 226 nodes in a cycle_ when trying to convert mediapipe facemesh [model](https://github.com/vladmandic/human/tree/main/models). Any help to fix this issue ? Thanks.

**Comment by patlevin** [comment]
Bonjour !

I have been able to reproduce the issue and I am looking into it right now.
Thank you for letting me know about this problem.

I will try to fix this ASAP.

**Comment by patlevin** [comment]
The problem only exists in the latest version (I introduced this bug when trying to fix a different problem).

As a quick workaround you can use v1.6.0 instead, which doesn't have this problem.

**Comment by zighem25** [comment]
Many thanks @patlevin it works with v1.6.0
