### ISSUE TITLE
the size of quant model seems not right

### ISSUE THREAD

**Issue by willfu** [patlevin/tfjs-to-tf#6]
when I use this tool to convert the quant model such as posenet mobilenet_quant2_100, the size of the frozen model converted seems the same with float one, while not quantization, is it normal? thanks.

**Comment by patlevin** [comment]
Weights are automatically dequantised by TFJS so it's normal.
Quantised models therefore cannot be converted as-is.

**Comment by willfu** [comment]
Thanks for the reply. But it seems the model dequantised is not right, I just use the model that could not detect normal as the float one, I guess there is some issue of this converted model. @patlevin

**Comment by patlevin** [comment]
@willfu Quant models have problems when converted back to float. It's best to only convert float models and do [Post-training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) in TF or TFLite.
