### ISSUE TITLE
setup.py needs installed tensorflowjs

### ISSUE THREAD

**Issue by allo-** [patlevin/tfjs-to-tf#8]
The `setup.py` file imports `tfjs_graph_converter.version.py` and that indirectly imports `tfjs_graph_converter.__init__.py`.

This makes it impossible to install your package using pip, when `tensorflowjs` is not installed, yet.

The easiest way would probably be to move `version.py` to the top-level or to write the version directly into `setup.py`.

In addition it would be great when you would publish your package to pypi.

**Comment by patlevin** [comment]
Thanks for bringing the installation issue to my attention- it is already fixed and will be part of the next release.

I will consider publishing the package on pypi once the next release is ready.

**Comment by allo-** [comment]
You seem not to have pushed this commit, yet.

It would be good when you can just push it, because I can include the repo into requirements.txt until you publish a package, but currently I need to document a separate installation step to first install tensorflowjs and then your package.

Thank you for the fix and your useful tool. I am using it in https://github.com/allo-/virtual_webcam_background to work with body-pix.

**Comment by patlevin** [comment]
>You seem not to have pushed this commit, yet.

Whoops - my bad, sorry 😀
